import { useRef, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import Navbar from './components/Navbar'; import Hero from './components/Hero'; import InputCard from './components/InputCard'; import Loading from './components/Loading'; import ErrorCard from './components/ErrorCard'; import FlashcardList from './components/FlashcardList'; import Quiz from './components/Quiz'; import StudyProgress from './components/StudyProgress'; import Footer from './components/Footer';
import { createStudySet, getErrorMessage } from './api/studyApi';

export default function App() {
  const [dark, setDark] = useState(false), [notes, setNotes] = useState(''), [data, setData] = useState(null), [loading, setLoading] = useState(false), [error, setError] = useState(''), [tab, setTab] = useState('flashcards');
  const controller = useRef(null), requestId = useRef(0);
  const generate = async () => { controller.current?.abort(); const id = ++requestId.current; const nextController = new AbortController(); controller.current = nextController; setLoading(true); setError(''); try { const response = await createStudySet(notes, nextController.signal); if (id === requestId.current) { setData(response); setTab('flashcards'); } } catch (err) { const message = getErrorMessage(err); if (message && id === requestId.current) setError(message); } finally { if (id === requestId.current) setLoading(false); } };
  const cancel = () => { requestId.current += 1; controller.current?.abort(); controller.current = null; setLoading(false); };
  const start = () => document.getElementById('studio')?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  const panel = data && (tab === 'flashcards' ? <FlashcardList cards={data.flashcards}/> : tab === 'quiz' ? <Quiz quiz={data.quiz}/> : <StudyProgress data={data}/>);
  return <div className={dark ? 'app dark' : 'app'}><Navbar dark={dark} onToggle={() => setDark(!dark)}/><main><Hero onStart={start}/><InputCard {...{ notes, setNotes, loading, onGenerate: generate, onCancel: cancel }}/><section className="results shell" aria-live="polite"><AnimatePresence mode="wait">{loading && <Loading />}{!loading && error && <ErrorCard message={error} onRetry={generate}/>} {!loading && data && <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}><div className="summary-card"><div><p className="eyebrow">Your study brief</p><h2>{data.difficulty} focus</h2><p>{data.summary || 'A structured set, ready when you are.'}</p></div><span className="pill">AI crafted</span></div><div className="tabs" role="tablist" aria-label="Study views">{['flashcards', 'quiz', 'progress'].map((name) => <button key={name} role="tab" aria-selected={tab === name} className={tab === name ? 'active' : ''} onClick={() => setTab(name)}>{name}</button>)}</div><AnimatePresence mode="wait"><motion.div key={tab} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>{panel}</motion.div></AnimatePresence></motion.div>}</AnimatePresence></section></main><Footer /></div>;
}
