import { useState } from 'react';
import { HiArrowRight, HiArrowPath, HiCheckCircle } from 'react-icons/hi2';
import Question from './Question';
import ProgressBar from './ProgressBar';
export default function Quiz({ quiz }) { const [questions, setQuestions] = useState(quiz); const [index, setIndex] = useState(0); const [answers, setAnswers] = useState([]); const [selected, setSelected] = useState(null); const [reveal, setReveal] = useState(false); const [complete, setComplete] = useState(false); const item = questions[index];
  const advance = () => { setAnswers((history) => [...history, selected]); if (index === questions.length - 1) { setComplete(true); return; } setIndex(index + 1); setSelected(null); setReveal(false); };
  const retry = (incorrectOnly = false) => { const next = incorrectOnly ? questions.filter((question, i) => answers[i] !== question.correctAnswer) : quiz; setQuestions(next); setIndex(0); setAnswers([]); setSelected(null); setReveal(false); setComplete(false); };
  if (!questions.length) return <div className="empty-state">No quiz questions were generated for this material.</div>;
  if (complete) { const score = answers.filter((answer, i) => answer === questions[i].correctAnswer).length; const wrong = questions.length - score; return <div className="quiz-result"><HiCheckCircle /><p className="eyebrow">Quiz complete</p><h2>{score} <span>/ {questions.length}</span></h2><p>{score === questions.length ? 'A perfect run. You own this material.' : 'A strong start. Revisit the tricky bits and it will click.'}</p><div><button className="secondary-button" onClick={() => retry(false)}><HiArrowPath /> Start again</button>{wrong > 0 && <button className="primary-button" onClick={() => retry(true)}>Retry {wrong} incorrect</button>}</div></div>; }
  return <div className="study-panel quiz-panel"><div className="deck-header"><div><p className="eyebrow">Knowledge check</p><h2>One at a time</h2></div><span className="pill">Question {index + 1}</span></div><ProgressBar value={index + 1} total={questions.length}/><Question question={item} selected={selected} onSelect={setSelected} revealed={reveal}/><button className="primary-button quiz-next" disabled={selected === null} onClick={() => reveal ? advance() : setReveal(true)}>{reveal ? (index === questions.length - 1 ? 'See results' : 'Next question') : 'Check answer'} <HiArrowRight /></button></div>; }
